
-- DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    SENHA TEXT NOT NULL,
    email text not null
);

CREATE TABLE IF NOT EXISTS books (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    TITULO TEXT NOT NULL,
    USER_ID INTEGER REFERENCES users
);

CREATE TABLE IF NOT EXISTS filmes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    TITULO TEXT NOT NULL,
    USER_ID INTEGER REFERENCES users
);